
import os

file_path = r'C:\agri_crm\templates\transactions\sales_form_v2.html'

# Safe Python script to generate the template without line wrapping inside tags

lines = []
lines.append("{% extends 'base.html' %}")
lines.append("{% load humanize %}")
lines.append("")
lines.append("{% block content %}")
lines.append('<div x-data="salesForm()" class="flex flex-col xl:flex-row min-h-screen bg-[#F8F9FA]">')
lines.append('    <main class="flex-1 min-w-0 p-6 md:p-10 lg:p-12 pb-32">')
lines.append('        <div class="max-w-5xl mx-auto space-y-8">')
lines.append('            <header class="flex flex-col gap-2">')
lines.append('                <div class="flex items-center gap-2 text-gray-400 text-xs font-bold uppercase tracking-widest">')
lines.append('                    <span class="bg-green-50 text-green-600 px-2 py-1 rounded">Transactions</span><span>•</span>')
lines.append('                    <span>{% if invoice %}Edit Sale{% else %}New Sale{% endif %}</span>')
lines.append('                </div>')
lines.append('                <h1 class="text-4xl md:text-5xl font-bold text-gray-900 tracking-tight">{% if invoice %}Edit Sale{% else %}New Sale{% endif %}</h1>')
lines.append('                <p class="text-gray-500">{% if invoice %}Modify sales invoice #{{ invoice.invoice_number }}{% else %}Create a new sales invoice{% endif %}</p>')
lines.append('            </header>')

lines.append('            {% if error %}')
lines.append('            <div class="bg-red-50 border border-red-200 text-red-700 px-6 py-4 rounded-2xl" role="alert">')
lines.append('                <strong class="font-bold">Error!</strong><span class="block sm:inline">{{ error }}</span>')
lines.append('            </div>')
lines.append('            {% endif %}')

lines.append('            <form method="POST"')
lines.append('                action="{% if invoice %}{% url \'edit_sale\' invoice.pk %}{% else %}{% url \'create_sale\' %}{% endif %}"')
lines.append('                id="sales-form">')
lines.append('                {% csrf_token %}')

lines.append('                <div class="bg-white rounded-[2rem] p-8 shadow-sm border border-gray-100 mb-8 grid grid-cols-1 md:grid-cols-2 gap-8">')
lines.append('                    <div>')
lines.append('                        <label class="text-[10px] font-bold uppercase tracking-widest text-gray-400 pl-1 mb-2 block">Customer</label>')
lines.append('                        <div class="relative group" @click.away="customerOpen = false">')
lines.append('                            <input type="hidden" name="customer" x-model="customerId">')
lines.append('                            <input type="text" x-model="customerSearch" @input.debounce.300ms="searchCustomers()" @focus="customerOpen = true" placeholder="Search by Name or Mobile..." class="w-full h-14 bg-gray-50 rounded-2xl px-5 font-medium text-gray-900 border border-transparent hover:border-gray-200 focus:border-green-500/20 focus:bg-white outline-none transition-all placeholder-gray-400">')
lines.append('                            <div x-show="customerOpen" class="absolute top-full left-0 right-0 mt-2 bg-white border border-gray-100 rounded-2xl shadow-xl z-50 max-h-64 overflow-y-auto" style="display: none;">')
lines.append('                                <template x-for="c in customerResults" :key="c.id">')
lines.append('                                    <div @click="selectCustomer(c)" class="px-5 py-3 hover:bg-gray-50 cursor-pointer border-b border-gray-50 last:border-none">')
lines.append('                                        <div class="font-bold text-gray-900" x-text="c.name"></div>')
lines.append('                                        <div class="text-xs text-gray-500"><span x-text="c.city"></span> • <span x-text="c.mobile_no"></span></div>')
lines.append('                                    </div>')
lines.append('                                </template>')
lines.append('                                <div x-show="customerResults.length === 0 && customerSearch.length > 1" class="p-4 text-center">')
lines.append('                                    <p class="text-gray-400 text-sm mb-2">No customers found</p>')
lines.append('                                    <button type="button" @click="openCustomerModal()" class="text-green-600 font-bold hover:underline text-sm">+ Add New Customer</button>')
lines.append('                                </div>')
lines.append('                            </div>')
lines.append('                        </div>')
lines.append('                    </div>')
lines.append('                    <div>')
lines.append('                        <label class="text-[10px] font-bold uppercase tracking-widest text-gray-400 pl-1 mb-2 block">Date</label>')
lines.append("                        <input type='date' name='date' value='{% if invoice %}{{ invoice.date|date:'Y-m-d' }}{% else %}{% now 'Y-m-d' %}{% endif %}' class='w-full h-14 bg-gray-50 rounded-2xl px-5 font-medium text-gray-900 border border-transparent hover:border-gray-200 focus:border-green-500/20 focus:bg-white outline-none transition-all'>")
lines.append('                    </div>')
lines.append('                </div>')

lines.append('                <div class="space-y-4">')
lines.append('                    <template x-for="(row, i) in rows" :key="row.id">')
lines.append('                        <div class="bg-white rounded-3xl p-6 border border-gray-100 shadow-sm relative">')
lines.append('                            <button type="button" @click="removeRow(i)" x-show="rows.length > 1" class="absolute top-4 right-4 p-2 text-gray-300 hover:text-red-500 hover:bg-red-50 rounded-xl transition-colors z-10">')
lines.append('                                <svg class="w-5 h-5" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><polyline points="3 6 5 6 21 6"></polyline><path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"></path></svg>')
lines.append('                            </button>')
lines.append('                            <div class="mb-4 relative group" @click.away="row.productOpen = false">')
lines.append('                                <div class="flex justify-between items-end mb-2">')
lines.append('                                    <label class="text-[10px] font-bold uppercase tracking-widest text-gray-400 pl-1 block">Product Search</label>')
lines.append('                                    <div class="flex gap-4 text-xs font-bold" x-show="row.batchId">')
lines.append('                                        <span class="text-gray-400">Mfg: <span class="text-gray-900" x-text="row.mfgDate || \'-\'"></span></span>')
lines.append('                                        <span class="text-gray-400">Exp: <span class="text-red-600" x-text="row.expDate || \'-\'"></span></span>')
lines.append('                                    </div>')
lines.append('                                </div>')
lines.append('                                <input type="hidden" name="product_id[]" :value="row.productId">')
lines.append('                                <input type="text" placeholder="Type to search products..." x-model="row.productName" @input.debounce.300ms="searchProducts(row)" @focus="row.productOpen = true" class="w-full h-14 bg-gray-50 rounded-2xl px-5 font-medium text-gray-900 border border-transparent hover:border-gray-200 focus:border-green-500/20 focus:bg-white outline-none transition-all placeholder-gray-400 text-lg">')
lines.append('                                <div x-show="row.productOpen && row.productResults.length > 0" class="absolute top-full left-0 right-0 mt-2 bg-white border border-gray-100 rounded-2xl shadow-xl z-50 max-h-64 overflow-y-auto" style="display: none;">')
lines.append('                                    <template x-for="p in row.productResults" :key="p.id">')
lines.append('                                        <div @click="selectProduct(row, p)" class="px-5 py-3 hover:bg-gray-50 cursor-pointer border-b border-gray-50 last:border-none">')
lines.append('                                            <div class="font-bold text-gray-900" x-text="p.name"></div><div class="text-xs text-gray-500" x-text="p.tax_rate + \'% Tax\'"></div>')
lines.append('                                        </div>')
lines.append('                                    </template>')
lines.append('                                </div>')
lines.append('                            </div>')
lines.append('                            <div class="grid grid-cols-2 md:grid-cols-4 lg:grid-cols-7 gap-4 items-start">')
lines.append('                                <div class="col-span-1">')
lines.append('                                    <label class="text-[10px] font-bold uppercase tracking-widest text-gray-400 pl-1 mb-2 block">Size</label>')
lines.append('                                    <select x-model="row.selectedSizeIdx" x-init="$nextTick(() => { $el.value = row.selectedSizeIdx.toString() })" @change="selectSize(row)" class="w-full h-12 bg-gray-50 rounded-xl px-2 font-medium text-gray-900 border border-transparent hover:border-gray-200 focus:border-green-500/20 focus:bg-white outline-none transition-all text-sm">')
lines.append('                                        <option value="">Select</option><template x-for="(s, idx) in row.sizes" :key="idx"><option :value="idx" x-text="s.label"></option></template>')
lines.append('                                    </select>')
lines.append('                                </div>')
lines.append('                                <div class="col-span-1 md:col-span-2">')
lines.append('                                    <label class="text-[10px] font-bold uppercase tracking-widest text-gray-400 pl-1 mb-2 block">Batch</label>')
lines.append('                                    <select name="batch_id[]" x-model="row.batchId" x-init="$nextTick(() => { $el.value = row.batchId.toString() })" @change="selectBatch(row)" class="w-full h-12 bg-gray-50 rounded-xl px-2 font-medium text-gray-900 border border-transparent hover:border-gray-200 focus:border-green-500/20 focus:bg-white outline-none transition-all text-sm">')
lines.append('                                        <option value="">Batch</option><template x-for="batch in row.batches" :key="batch.id"><option :value="batch.id" x-text="batch.batch_number"></option></template>')
lines.append('                                    </select>')
lines.append('                                </div>')
lines.append('                                <div class="col-span-1"><label class="text-[10px] font-bold uppercase tracking-widest text-gray-400 pl-1 mb-2 block">Stock</label><div class="h-12 bg-gray-100 rounded-xl px-2 flex items-center justify-center text-sm text-gray-500 font-bold"><span x-text="row.stock || \'—\'"></span></div></div>')
lines.append('                                <div class="col-span-1"><label class="text-[10px] font-bold uppercase tracking-widest text-gray-400 pl-1 mb-2 block">Qty</label><input type="number" name="qty[]" x-model.number="row.qty" @input="calculateRow(row)" min="0" :max="row.stock" class="w-full h-12 bg-gray-50 rounded-xl px-2 font-bold text-gray-900 border border-transparent hover:border-gray-200 focus:border-green-500/20 focus:bg-white outline-none transition-all text-center text-lg"></div>')
lines.append('                                <div class="col-span-1"><label class="text-[10px] font-bold uppercase tracking-widest text-gray-400 pl-1 mb-2 block">Price</label><input type="number" step="0.01" name="price[]" x-model.number="row.price" @input="calculateRow(row)" class="w-full h-12 bg-gray-50 rounded-xl px-2 font-medium text-gray-900 border border-transparent hover:border-gray-200 focus:border-green-500/20 focus:bg-white outline-none transition-all text-center"></div>')
lines.append('                                <div class="col-span-1"><label class="text-[10px] font-bold uppercase tracking-widest text-gray-400 pl-1 mb-2 block">Total</label><div class="h-12 bg-green-50 rounded-xl px-2 flex items-center justify-center overflow-hidden"><span class="text-sm md:text-base font-bold text-green-600">&#8377;<span x-text="row.total.toFixed(2)"></span></span></div></div>')
lines.append('                            </div>')
lines.append('                        </div>')
lines.append('                    </template>')
lines.append('                    <button type="button" @click="addRow()" class="w-full py-6 border-2 border-dashed border-gray-200 rounded-3xl text-gray-400 hover:text-green-600 hover:border-green-400 hover:bg-green-50/50 transition-all font-bold flex items-center justify-center gap-2">Add Another Item</button>')
lines.append('                </div>')
lines.append('                <button type="submit" id="main-submit-btn" class="hidden">Submit</button>')
lines.append('            </form>')
lines.append('        </div>')
lines.append('    </main>')

lines.append('    <aside class="xl:w-[420px] bg-white border-l border-gray-100 z-40 relative">')
lines.append('        <div class="xl:fixed xl:w-[420px] h-full flex flex-col">')
lines.append('            <div class="p-8 pb-4 border-b border-gray-50 hidden xl:block"><h2 class="text-lg font-bold text-gray-900">Bill Summary</h2><p class="text-sm text-gray-400 mt-1">Review before completing</p></div>')
lines.append('            <div class="flex-1 p-8 space-y-6 overflow-y-auto">')
lines.append('                <div class="space-y-4">')
lines.append('                    <div class="flex justify-between items-center py-3 border-b border-gray-50"><span class="text-gray-500">Items</span><span class="font-bold text-gray-900" x-text="rows.length"></span></div>')
lines.append('                    <div class="flex justify-between items-center py-3 border-b border-gray-50"><span class="text-gray-500">Total Quantity</span><span class="font-bold text-gray-900" x-text="totalQty()"></span></div>')
lines.append('                    <div class="flex justify-between items-center py-3 border-b border-gray-50"><span class="text-gray-500">Subtotal</span><span class="font-bold text-gray-900">&#8377;<span x-text="grandTotal()"></span></span></div>')
lines.append('                </div>')
lines.append('                <div class="bg-green-50 rounded-2xl p-6 border border-green-100"><div class="text-xs font-bold uppercase tracking-widest text-green-600 mb-2">Grand Total</div><div class="text-4xl font-bold text-gray-900">&#8377;<span x-text="grandTotal()"></span></div></div>')
lines.append('                <div class="space-y-3">')
lines.append('                    <label class="text-[10px] font-bold uppercase tracking-widest text-gray-400 block">Payment Status</label>')
lines.append('                    <div class="flex bg-gray-100 rounded-xl p-1">')
lines.append('                        <button type="button" @click="paymentStatus = \'UNPAID\'" :class="paymentStatus === \'UNPAID\' ? \'bg-white shadow text-gray-900\' : \'text-gray-500\'" class="flex-1 py-3 rounded-lg font-bold text-sm transition-all">Unpaid</button>')
lines.append('                        <button type="button" @click="paymentStatus = \'PARTIAL\'" :class="paymentStatus === \'PARTIAL\' ? \'bg-white shadow text-gray-900\' : \'text-gray-500\'" class="flex-1 py-3 rounded-lg font-bold text-sm transition-all">Partial</button>')
lines.append('                        <button type="button" @click="paymentStatus = \'PAID\'; amountReceived = parseFloat(grandTotal())" :class="paymentStatus === \'PAID\' ? \'bg-green-500 text-white shadow\' : \'text-gray-500\'" class="flex-1 py-3 rounded-lg font-bold text-sm transition-all">Paid</button>')
lines.append('                    </div>')
lines.append('                    <input type="hidden" name="payment_status" :value="paymentStatus" form="sales-form">')
lines.append('                </div>')
lines.append('                <div x-show="paymentStatus === \'PARTIAL\'" x-transition class="space-y-2">')
lines.append('                    <label class="text-[10px] font-bold uppercase tracking-widest text-gray-400 block">Amount Received</label>')
lines.append('                    <input type="number" step="0.01" name="amount_received" x-model.number="amountReceived" form="sales-form" class="w-full h-14 bg-gray-50 rounded-2xl px-5 font-bold text-gray-900 border border-transparent focus:border-green-500/20 focus:bg-white outline-none transition-all text-center text-xl">')
lines.append('                </div>')
lines.append('            </div>')
lines.append('            <div class="p-8 pt-4 border-t border-gray-50">')
lines.append('                <button type="button" @click="document.getElementById(\'main-submit-btn\').click()" class="bg-green-600 hover:bg-green-700 text-white w-full py-5 rounded-2xl font-bold text-lg shadow-xl shadow-green-600/20 hover:shadow-green-600/30 active:scale-[0.98] transition-all flex items-center justify-center gap-3">Complete Sale</button>')
lines.append('            </div>')
lines.append('        </div>')
lines.append('    </aside>')
lines.append('    <datalist id="product-list"></datalist>')

# Modal
lines.append('    <div x-show="showCustomerModal" class="fixed inset-0 z-[60] flex items-center justify-center bg-black/60 backdrop-blur-sm" style="display: none;" x-transition.opacity>')
lines.append('        <div class="bg-white rounded-3xl p-8 w-full max-w-md shadow-2xl" @click.away="showCustomerModal = false">')
lines.append('            <h3 class="text-2xl font-bold mb-6 text-gray-900">Add New Customer</h3>')
lines.append('            <div class="space-y-4">')
lines.append('                <div><label class="text-xs font-bold text-gray-400 uppercase">Customer Name</label><input type="text" x-model="newCustomerName" class="w-full h-12 px-4 bg-gray-50 border border-gray-200 rounded-xl focus:border-green-500 focus:bg-white outline-none transition-all" placeholder="Enter name"></div>')
lines.append('                <div><label class="text-xs font-bold text-gray-400 uppercase">Mobile Number</label><input type="text" x-model="newCustomerMobile" class="w-full h-12 px-4 bg-gray-50 border border-gray-200 rounded-xl focus:border-green-500 focus:bg-white outline-none transition-all" placeholder="Enter mobile"></div>')
lines.append('                <div><label class="text-xs font-bold text-gray-400 uppercase">City / Village</label><input type="text" x-model="newCustomerCity" class="w-full h-12 px-4 bg-gray-50 border border-gray-200 rounded-xl focus:border-green-500 focus:bg-white outline-none transition-all" placeholder="Enter city or village"></div>')
lines.append('            </div>')
lines.append('            <div class="flex gap-3 mt-8"><button type="button" @click="showCustomerModal = false" class="flex-1 py-3 bg-gray-100 hover:bg-gray-200 font-bold text-gray-600 rounded-xl transition-colors">Cancel</button><button type="button" @click="saveNewCustomer()" class="flex-1 py-3 bg-green-600 hover:bg-green-700 font-bold text-white rounded-xl shadow-lg shadow-green-600/20 transition-all">Save Customer</button></div>')
lines.append('        </div>')
lines.append('    </div>')
lines.append('</div>')

# JS
lines.append('<script>')
lines.append('    function salesForm() {')
# CRITICAL: NO NEWLINES in the Django tags below
lines.append('        const existingItems = {{ existing_items_json|safe|default:"[]" }};')
lines.append('        const existingCustomer = {% if invoice and invoice.customer %}{ id: {{ invoice.customer.id }}, name: "{{ invoice.customer.name }}", city: "{{ invoice.customer.city|default:\'\' }}", mobile_no: "{{ invoice.customer.mobile_no|default:\'\' }}" }{% else %}null{% endif %};')

lines.append('        let initialRows = [];')
lines.append('        if (existingItems.length > 0) {')
lines.append('            initialRows = existingItems.map((item, idx) => ({')
lines.append('                id: Date.now() + idx, productName: item.product_name || "", productId: item.product_id || "", productOpen: false, productResults: [],')
lines.append('                sizes: item.size_label ? [{ size: item.size, unit: item.unit, label: item.size_label }] : [],')
lines.append('                selectedSizeIdx: item.size_label ? 0 : "",')
lines.append('                batches: [{ id: item.batch_id, batch_number: item.batch_number, quantity: item.current_stock, price: item.price, manufacturing_date: item.mfg_date, expiry_date: item.expiry_date }],')
lines.append('                batchId: item.batch_id ? String(item.batch_id) : "", stock: item.current_stock || 0, qty: item.qty || 1, price: item.price || 0, total: item.total || 0, mfgDate: item.mfg_date || "", expDate: item.expiry_date || ""')
lines.append('            }));')
lines.append('        } else {')
lines.append('            initialRows = [{ id: Date.now(), productName: "", productId: "", productOpen: false, productResults: [], sizes: [], selectedSizeIdx: "", batches: [], batchId: "", stock: 0, qty: 1, price: 0, total: 0, mfgDate: "", expDate: "" }];')
lines.append('        }')

lines.append('        return {')
lines.append('            customerSearch: existingCustomer ? `${existingCustomer.name} (${existingCustomer.city}) - ${existingCustomer.mobile_no}` : "",')
lines.append('            customerId: existingCustomer ? existingCustomer.id : "", customerOpen: false, customerResults: [],')
lines.append('            showCustomerModal: false, newCustomerName: "", newCustomerMobile: "", newCustomerCity: "",')
lines.append('            rows: initialRows,')
lines.append("            paymentStatus: {% if invoice %}'{{ invoice.payment_status }}'{% else %}'PAID'{% endif %},")
lines.append("            amountReceived: {% if invoice %}{{ invoice.amount_received|default:0 }}{% else %}0{% endif %},")

lines.append('            async searchCustomers() { if (this.customerSearch.length < 2) { this.customerResults = []; return; } const res = await fetch(`{% url "search_customers" %}?q=${this.customerSearch}`); this.customerResults = await res.json(); this.customerOpen = true; },')
lines.append('            selectCustomer(c) { this.customerId = c.id; this.customerSearch = `${c.name} (${c.city}) - ${c.mobile_no}`; this.customerOpen = false; },')
lines.append('            openCustomerModal() { this.newCustomerName = this.customerSearch; this.showCustomerModal = true; this.customerOpen = false; },')
lines.append('            async saveNewCustomer() { if (!this.newCustomerName || !this.newCustomerMobile) { alert("Name and Mobile are required"); return; } const res = await fetch("{% url "create_customer_ajax" %}", { method: "POST", headers: { "Content-Type": "application/json", "X-CSRFToken": document.querySelector("[name=csrfmiddlewaretoken]").value }, body: JSON.stringify({ name: this.newCustomerName, mobile_no: this.newCustomerMobile, city: this.newCustomerCity }) }); const data = await res.json(); if (data.success) { this.selectCustomer(data); this.showCustomerModal = false; this.newCustomerName = ""; this.newCustomerMobile = ""; this.newCustomerCity = ""; } else { alert(data.error || "Failed"); } },')
lines.append('            async searchProducts(row) { if (row.productName.length < 2) { row.productResults = []; return; } const res = await fetch(`{% url "search_products" %}?q=${row.productName}&format=json`); row.productResults = await res.json(); row.productOpen = true; },')
lines.append('            async selectProduct(row, p) { row.productId = p.id; row.productName = p.name; row.productOpen = false; row.sizes = []; row.selectedSizeIdx = ""; row.batches = []; row.batchId = ""; row.stock = 0; row.price = 0; row.mfgDate = ""; row.expDate = ""; const res = await fetch(`{% url "get_product_sizes" %}?product_id=${p.id}`); row.sizes = await res.json(); },')
lines.append('            async selectSize(row) { row.batches = []; row.batchId = ""; row.stock = 0; row.price = 0; row.mfgDate = ""; row.expDate = ""; if (row.selectedSizeIdx === "") return; const sizeObj = row.sizes[row.selectedSizeIdx]; const res = await fetch(`{% url "get_batches_for_product" %}?product_id=${row.productId}&size=${sizeObj.size}&unit=${sizeObj.unit}`); row.batches = await res.json(); },')
lines.append('            selectBatch(row) { const batch = row.batches.find(b => b.id == row.batchId); if (batch) { row.stock = batch.quantity; row.price = batch.price; row.mfgDate = batch.manufacturing_date || ""; row.expDate = batch.expiry_date || ""; } else { row.stock = 0; row.price = 0; row.mfgDate = ""; row.expDate = ""; } this.calculateRow(row); },')
lines.append('            addRow() { this.rows.push({ id: Date.now(), productName: "", productId: "", productOpen: false, productResults: [], sizes: [], selectedSizeIdx: "", batches: [], batchId: "", stock: 0, qty: 1, price: 0, total: 0 }); },')
lines.append('            removeRow(index) { if (this.rows.length > 1) { this.rows.splice(index, 1); } },')
lines.append('            calculateRow(row) { if (row.qty < 0) row.qty = 0; if (row.stock > 0 && row.qty > row.stock) row.qty = row.stock; row.total = row.qty * row.price; if (this.paymentStatus === "PAID") this.amountReceived = parseFloat(this.grandTotal()); },')
lines.append('            totalQty() { return this.rows.reduce((sum, row) => sum + (row.qty || 0), 0); },')
lines.append('            grandTotal() { return this.rows.reduce((sum, row) => sum + row.total, 0).toFixed(2); }')
lines.append('        }')
lines.append('    }')
lines.append('</script>')
lines.append('{% endblock %}')

with open(file_path, 'w', encoding='utf-8') as f:
    f.write('\n'.join(lines))
    print(f"Successfully wrote {len(lines)} lines to {file_path}")
