# Generated by Django 6.0 on 2026-03-31 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master_data', '0011_product_identity_pair_constraint'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('crop_type', models.CharField(choices=[('KHARIF', 'Kharif'), ('RABI', 'Rabi'), ('BOTH', 'Both / Year-round')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CultivationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acreage', models.DecimalField(decimal_places=2, help_text='Acres allocated to this crop', max_digits=8)),
                ('season', models.CharField(choices=[('KHARIF', 'Kharif'), ('RABI', 'Rabi')], max_length=10)),
                ('season_year', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('ACTIVE', 'Active'), ('HARVESTED', 'Harvested')], default='ACTIVE', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cultivation_records', to='farming.cropmaster')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cultivation_records', to='master_data.customer')),
            ],
            options={
                'ordering': ['-season_year', 'season', 'crop__name'],
            },
        ),
        migrations.CreateModel(
            name='CropProductNorm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_rate', models.DecimalField(decimal_places=3, help_text='Quantity per acre', max_digits=10)),
                ('unit', models.CharField(help_text='Unit of measurement (mirrors Product.unit_type)', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='norms', to='farming.cropmaster')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='crop_norms', to='master_data.product')),
            ],
            options={
                'unique_together': {('crop', 'product')},
            },
        ),
    ]
