# Generated by Django 5.0.6 on 2026-04-04 16:25

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farming', '0001_initial'),
        ('master_data', '0012_agcdss_phase1'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgronomistProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(help_text='Unique employee identifier (e.g., EMP-001)', max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(choices=[('field_officer', 'Field Officer'), ('agronomist', 'Senior Agronomist'), ('consultant', 'Consultant')], default='field_officer', max_length=50)),
                ('zone', models.CharField(help_text='Geographic coverage area', max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'farming_agronomist_profile',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FieldVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_number', models.CharField(help_text='Auto-generated: FV-YYYYMMDD-NNNN', max_length=20, unique=True)),
                ('visit_date', models.DateField()),
                ('visit_time', models.TimeField(blank=True, null=True)),
                ('purpose', models.CharField(choices=[('routine', 'Routine Scouting'), ('complaint', 'Complaint'), ('follow_up', 'Follow-up'), ('seasonal', 'Seasonal Assessment')], default='routine', max_length=20)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agronomist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_visits', to='farming.agronomistprofile')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_visits', to='master_data.customer')),
            ],
            options={
                'db_table': 'farming_field_visit',
                'ordering': ['-visit_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FieldConsultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultation_number', models.CharField(help_text='Auto-generated: FC-YYYYMMDD-NNNN', max_length=20, unique=True)),
                ('consultation_date', models.DateField(default=datetime.date.today)),
                ('consultation_time', models.TimeField(blank=True, null=True)),
                ('weather_conditions', models.CharField(blank=True, help_text='Clear / Overcast / Humid / Dry', max_length=50)),
                ('crop_stage', models.CharField(blank=True, help_text='Vegetative / Flowering / Fruiting / Pre-harvest', max_length=50)),
                ('general_observations', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('closed', 'Closed')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agronomist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultations', to='farming.agronomistprofile')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_consultations', to='master_data.customer')),
                ('field_visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultations', to='farming.fieldvisit')),
            ],
            options={
                'db_table': 'farming_field_consultation',
                'ordering': ['-consultation_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PestDiseaseCropLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pest_disease_links', to='farming.cropmaster')),
            ],
            options={
                'db_table': 'farming_pest_disease_crop_link',
            },
        ),
        migrations.CreateModel(
            name='PestDiseaseLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Standard name of pest/disease', max_length=150, unique=True)),
                ('local_name', models.CharField(blank=True, help_text='Local language name', max_length=150)),
                ('type', models.CharField(choices=[('pest', 'Pest'), ('disease', 'Disease'), ('deficiency', 'Nutrient Deficiency'), ('weed', 'Weed')], help_text='Classification type', max_length=20)),
                ('symptoms', models.TextField(help_text='Visual indicators and symptoms')),
                ('management_notes', models.TextField(blank=True, help_text='General management and control notes')),
                ('photo', models.ImageField(blank=True, help_text='Reference photo', null=True, upload_to='pest_disease/')),
                ('is_active', models.BooleanField(default=True)),
                ('affected_crops', models.ManyToManyField(blank=True, help_text='Crops affected by this pest/disease', related_name='pest_diseases', through='farming.PestDiseaseCropLink', to='farming.cropmaster')),
            ],
            options={
                'db_table': 'farming_pest_disease_library',
                'ordering': ['type', 'name'],
            },
        ),
        migrations.AddField(
            model_name='pestdiseasecroplink',
            name='pest_disease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crop_links', to='farming.pestdiseaselibrary'),
        ),
        migrations.CreateModel(
            name='DiagnosisLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('affected_area_acres', models.DecimalField(decimal_places=2, help_text='Portion of plot affected', max_digits=6)),
                ('symptoms_observed', models.TextField(blank=True)),
                ('field_photo', models.ImageField(blank=True, null=True, upload_to='diagnosis/')),
                ('sequence', models.PositiveIntegerField(default=0, help_text='Row ordering')),
                ('cultivation_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnoses', to='farming.cultivationrecord')),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis_lines', to='farming.fieldconsultation')),
                ('pest_disease', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diagnosis_lines', to='farming.pestdiseaselibrary')),
            ],
            options={
                'db_table': 'farming_diagnosis_line',
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plot_name', models.CharField(help_text='Plot identifier (e.g., "North Field", "River Side")', max_length=100)),
                ('area_acres', models.DecimalField(decimal_places=2, help_text='Total area in acres', max_digits=6)),
                ('soil_type', models.CharField(blank=True, choices=[('sandy', 'Sandy'), ('loamy', 'Loamy'), ('clay', 'Clay'), ('black_cotton', 'Black Cotton')], help_text='Soil classification', max_length=20)),
                ('gps_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='GPS Latitude')),
                ('gps_lon', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='GPS Longitude')),
                ('is_active', models.BooleanField(default=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plots', to='master_data.customer')),
                ('village', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plots', to='master_data.village')),
            ],
            options={
                'db_table': 'farming_plot',
                'ordering': ['customer', 'plot_name'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage_per_acre', models.DecimalField(decimal_places=3, help_text='Amount per acre', max_digits=8)),
                ('dosage_unit', models.CharField(choices=[('kg', 'Kilogram'), ('ltr', 'Litre'), ('ml', 'Millilitre'), ('gm', 'Gram'), ('packet', 'Packet')], max_length=10)),
                ('total_quantity', models.DecimalField(decimal_places=3, help_text='Computed: dosage_per_acre × affected area', max_digits=10)),
                ('application_method', models.CharField(choices=[('spray', 'Spray'), ('drip', 'Drip Irrigation'), ('broadcast', 'Broadcast'), ('soil', 'Soil Application'), ('seed_treatment', 'Seed Treatment')], default='spray', max_length=20)),
                ('timing', models.CharField(blank=True, help_text='e.g., "Morning spray", "At 30 DAS"', max_length=100)),
                ('frequency', models.CharField(blank=True, help_text='e.g., "Once", "Weekly × 3"', max_length=100)),
                ('status', models.CharField(choices=[('recommended', 'Recommended'), ('dispensed', 'Dispensed'), ('applied', 'Applied'), ('cancelled', 'Cancelled')], default='recommended', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('sequence', models.PositiveIntegerField(default=0, help_text='Row ordering')),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescription_lines', to='farming.fieldconsultation')),
                ('diagnosis_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to='farming.diagnosisline')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='master_data.product')),
            ],
            options={
                'db_table': 'farming_prescription_line',
                'ordering': ['sequence'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='pestdiseasecroplink',
            unique_together={('pest_disease', 'crop')},
        ),
        migrations.AddConstraint(
            model_name='plot',
            constraint=models.UniqueConstraint(fields=('customer', 'plot_name'), name='unique_customer_plot_name'),
        ),
    ]
