# Generated by Django 5.0.6 on 2026-04-07 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farming', '0002_agcdss_phase1'),
        ('inventory', '0010_alter_batch_id_alter_stockbin_id_and_more'),
        ('transactions', '0029_alter_customerpayment_id_alter_deliverynote_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cropproductnorm',
            name='severity_adjustments',
            field=models.JSONField(blank=True, default=dict, help_text='Multipliers by severity, e.g. {"LOW": 0.8, "MEDIUM": 1.0, "HIGH": 1.3, "CRITICAL": 1.6}'),
        ),
        migrations.AddField(
            model_name='fieldconsultation',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fieldconsultation',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='User who approved the prescription', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_consultations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prescriptionline',
            name='chosen_batch',
            field=models.ForeignKey(blank=True, help_text='Batch selected during dispense', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescription_lines', to='inventory.batch'),
        ),
        migrations.AddField(
            model_name='prescriptionline',
            name='pack_quantity',
            field=models.PositiveIntegerField(blank=True, help_text='Number of packs to dispense', null=True),
        ),
        migrations.AddField(
            model_name='prescriptionline',
            name='sales_item',
            field=models.ForeignKey(blank=True, help_text='SalesItem created when dispensed', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescription_lines', to='transactions.salesitem'),
        ),
        migrations.AlterField(
            model_name='fieldconsultation',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('dispensed', 'Dispensed'), ('closed', 'Closed')], default='draft', max_length=20),
        ),
        migrations.CreateModel(
            name='ConsultationPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='consultation_photos/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('taken_at', models.DateTimeField(auto_now_add=True)),
                ('diagnosis_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='farming.diagnosisline')),
            ],
            options={
                'db_table': 'farming_consultation_photo',
                'ordering': ['taken_at'],
            },
        ),
    ]
