from django.urls import path
from . import views
from . import views_pipeline
from . import views_buying_pipeline

urlpatterns = [
    path('sales/new/', views.create_sale, name='create_sale'),
    path('search-products/', views.search_products, name='search_products'),
    path('get-product-details/', views.get_product_details, name='get_product_details'),
    path('get-batch-details/', views.get_batch_details, name='get_batch_details'),
    path('get-product-batches/', views.get_batches_for_product, name='get_batches_for_product'),
    path('get-product-sizes/', views.get_product_sizes, name='get_product_sizes'),
    path('search-customers/', views.search_customers, name='search_customers'),
    path('create-customer-ajax/', views.create_customer_ajax, name='create_customer_ajax'),
    path('get-customer-invoices/', views.get_customer_invoices, name='get_customer_invoices'),
    path('get-invoice-items/', views.get_invoice_items, name='get_invoice_items'),
    path('sales/', views.sales_list, name='sales_list'),
    path('sales/<int:pk>/', views.invoice_detail, name='invoice_detail'),
    path('sales/<int:pk>/edit/', views.edit_sale, name='edit_sale'),
    path('invoices/<int:pk>/delete/', views.delete_invoice, name='delete_invoice'),
    path('sales/<int:pk>/record-receipt/', views.record_receipt, name='record_receipt'),
    path('receipt/<int:pk>/delete/', views.delete_customer_payment, name='delete_customer_payment'),
    path('purchases/', views.purchase_list, name='purchase_list'),
    path('purchases/new/', views.create_purchase, name='create_purchase'),
    path('purchases/<int:pk>/', views.purchase_detail, name='purchase_detail'),
    path('purchases/<int:pk>/edit/', views.purchase_edit, name='purchase_edit'),
    path('purchases/<int:pk>/delete/', views.purchase_delete, name='purchase_delete'),
    path('transactions/payable/', views.accounts_payable, name='accounts_payable'),
    path('transactions/receivables/', views.customer_ledger, name='customer_ledger'),
    path('transactions/wallet/reverse/<int:payment_id>/', views.reverse_wallet_transaction, name='reverse_wallet_transaction'),
    path('invoice/<int:invoice_id>/settle-wallet/', views.settle_invoice_via_wallet, name='settle_invoice_via_wallet'),
    path('transactions/record-payment/', views.record_payment, name='record_payment'),
    path('payments/<int:pk>/', views.supplier_payment_detail, name='supplier_payment_detail'),
    path('payments/<int:pk>/cancel/', views.cancel_supplier_payment, name='cancel_supplier_payment'),
    path('payments/delete/<int:pk>/', views.delete_supplier_payment, name='delete_supplier_payment'),
    path('returns/', views.returns_list, name='returns_list'),
    path('returns/sales/new/', views.create_sales_return, name='create_sales_return'),
    path('returns/sales/<int:pk>/', views.sales_return_detail, name='sales_return_detail'),
    path('returns/sales/<int:pk>/delete/', views.delete_sales_return, name='delete_sales_return'),
    path('returns/purchase/new/', views.create_purchase_return, name='create_purchase_return'),
    path('returns/purchase/<int:pk>/', views.purchase_return_detail, name='purchase_return_detail'),
    path('returns/purchase/<int:pk>/delete/', views.delete_purchase_return, name='delete_purchase_return'),
    path('search-suppliers/', views.search_suppliers, name='search_suppliers'),
    path('get-supplier-invoices/', views.get_supplier_invoices, name='get_supplier_invoices'),
    path('get-purchase-invoice-items/', views.get_purchase_invoice_items, name='get_purchase_invoice_items'),
    path('create-supplier/', views.create_supplier, name='create_supplier'),
    path('create-product/', views.create_product, name='create_product'),
    path('customer/<int:pk>/statement/', views.customer_statement_view, name='customer_statement'),
    # Sprint 11: Submit actions
    path('sales/<int:pk>/submit/', views.submit_sales_invoice, name='submit_sales_invoice'),
    path('purchases/<int:pk>/submit/', views.submit_purchase_invoice, name='submit_purchase_invoice'),
    path('returns/sales/<int:pk>/submit/', views.submit_sales_return, name='submit_sales_return'),
    path('returns/purchase/<int:pk>/submit/', views.submit_purchase_return, name='submit_purchase_return'),
    # Sprint 15: Cancel actions
    path('sales/<int:pk>/cancel/', views.cancel_sales_invoice, name='cancel_sales_invoice'),
    path('purchases/<int:pk>/cancel/', views.cancel_purchase_invoice, name='cancel_purchase_invoice'),

    # Sprint 18: Buying Pipeline
    path('purchase-orders/', views_buying_pipeline.purchase_order_list, name='purchase_po_list'),
    path('purchase-orders/new/', views_buying_pipeline.create_purchase_order, name='create_purchase_order'),
    path('purchase-orders/<int:pk>/', views_buying_pipeline.purchase_order_detail, name='purchase_order_detail'),
    path('purchase-orders/<int:pk>/submit/', views_buying_pipeline.submit_purchase_order, name='submit_purchase_po'),
    path('purchase-orders/<int:pk>/cancel/', views_buying_pipeline.cancel_purchase_order, name='cancel_purchase_po'),
    
    path('purchase-receipts/', views_buying_pipeline.purchase_receipt_list, name='purchase_receipt_list'),
    path('purchase-receipts/new/', views_buying_pipeline.create_purchase_receipt, name='create_purchase_receipt'),
    path('purchase-receipts/<int:pk>/', views_buying_pipeline.purchase_receipt_detail, name='purchase_receipt_detail'),
    path('purchase-receipts/<int:pk>/submit/', views_buying_pipeline.submit_purchase_receipt, name='submit_purchase_receipt'),
    path('purchase-receipts/<int:pk>/cancel/', views_buying_pipeline.cancel_purchase_receipt, name='cancel_purchase_receipt'),

    # Sprint 17: Selling Pipeline 
    path('quotations/', views_pipeline.quotation_list, name='quotation_list'),
    path('quotations/new/', views_pipeline.create_quotation, name='create_quotation'),
    path('quotations/<int:pk>/', views_pipeline.quotation_detail, name='quotation_detail'),
    path('quotations/<int:pk>/submit/', views_pipeline.submit_quotation, name='submit_quotation'),
    path('quotations/<int:pk>/cancel/', views_pipeline.cancel_quotation, name='cancel_quotation'),
    
    path('sales-orders/', views_pipeline.sales_order_list, name='sales_order_list'),
    path('sales-orders/new/', views_pipeline.create_sales_order, name='create_sales_order'),
    path('sales-orders/<int:pk>/', views_pipeline.sales_order_detail, name='sales_order_detail'),
    path('sales-orders/<int:pk>/submit/', views_pipeline.submit_sales_order, name='submit_sales_order'),
    path('sales-orders/<int:pk>/cancel/', views_pipeline.cancel_sales_order, name='cancel_sales_order'),
    
    path('delivery-notes/', views_pipeline.delivery_note_list, name='delivery_note_list'),
    path('delivery-notes/new/', views_pipeline.create_delivery_note, name='create_delivery_note'),
    path('delivery-notes/<int:pk>/', views_pipeline.delivery_note_detail, name='delivery_note_detail'),
    path('delivery-notes/<int:pk>/submit/', views_pipeline.submit_delivery_note, name='submit_delivery_note'),
    path('delivery-notes/<int:pk>/cancel/', views_pipeline.cancel_delivery_note, name='cancel_delivery_note'),
]

