# Generated by Django 5.0.6 on 2025-12-12 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master_data', '0002_alter_category_id_alter_customer_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=50)),
                ('manufacturing_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mrp', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='MRP')),
                ('base_selling_price', models.DecimalField(decimal_places=2, help_text='Default selling price for this batch', max_digits=10)),
                ('current_quantity', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='master_data.product')),
            ],
            options={
                'unique_together': {('product', 'batch_number', 'mrp')},
            },
        ),
    ]
