# Generated by Django 5.0.6 on 2025-12-12 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='size',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='batch',
            name='unit',
            field=models.CharField(default='kg', max_length=20),
        ),
    ]
