# Generated by Django 6.0 on 2026-02-21 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_batch_id'),
        ('master_data', '0007_alter_category_id_alter_customer_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(help_text='Positive for inward, negative for outward.')),
                ('reference_document_type', models.CharField(help_text="E.g. 'PurchaseInvoice', 'SalesInvoice', 'ManualAdjustment'.", max_length=50)),
                ('reference_document_id', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='batch',
            constraint=models.CheckConstraint(check=models.Q(('current_quantity__gte', 0)), name='batch_non_negative_stock'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.batch'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['reference_document_type', 'reference_document_id'], name='idx_sm_ref_doc'),
        ),
    ]
