# Generated by Django 6.0 on 2026-02-21 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_add_stockmovement_ledger_and_check_constraint'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_quantity', models.IntegerField(help_text='System quantity at the time of reconciliation.')),
                ('new_quantity', models.IntegerField(help_text='Physical count entered by the admin.')),
                ('reason', models.CharField(choices=[('Damage', 'Damage / Spoilage'), ('Theft', 'Theft / Shrinkage'), ('Count Error', 'Count Error / Correction'), ('Other', 'Other')], default='Count Error', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reconciliations', to='inventory.batch')),
            ],
        ),
    ]
