# Generated by Django 6.0 on 2026-02-21 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_sprint8_seed_default_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='valuation_rate',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Per-unit cost at the time of this movement.', max_digits=15),
        ),
    ]
