# Generated by Django 5.0.6 on 2025-12-13 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_salesreturn_customer_alter_salesreturn_original_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoice',
            name='additional_discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='loading_charges',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
