# Generated by Django 5.0.6 on 2025-12-14 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_purchaseitem_basic_rate_purchaseitem_net_cost_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseitem',
            name='net_cost',
        ),
        migrations.RemoveField(
            model_name='purchaseitem',
            name='unit_cost',
        ),
    ]
