# Generated by Django 5.0.6 on 2025-12-25 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_salesinvoice_amount_received_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerpayment',
            name='payment_mode',
            field=models.CharField(choices=[('CASH', 'Cash'), ('UPI', 'UPI'), ('CHEQUE', 'Cheque'), ('BANK', 'Bank Transfer'), ('WALLET', 'Wallet')], default='UPI', max_length=20),
        ),
    ]
