# Generated by Django 5.0.6 on 2026-01-19 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_alter_customerpayment_payment_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerpayment',
            name='reversal_of',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversal_entry', to='transactions.customerpayment'),
        ),
        migrations.AlterField(
            model_name='customerpayment',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='transactions.salesinvoice'),
        ),
        migrations.AlterField(
            model_name='customerpayment',
            name='payment_mode',
            field=models.CharField(choices=[('CASH', 'Cash'), ('UPI', 'UPI'), ('CHEQUE', 'Cheque'), ('BANK', 'Bank Transfer'), ('WALLET', 'Wallet'), ('REFUND', 'Refund / Withdrawal'), ('WALLET_CREDIT', 'Wallet Credit')], default='UPI', max_length=20),
        ),
    ]
