# Generated by Django 6.0 on 2026-01-20 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0011_customerpayment_sales_return_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerpayment',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='transactions.salesinvoice'),
        ),
    ]
