# Generated by Django 5.0.6 on 2026-01-23 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0013_customerpayment_purchase_return_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerpayment',
            name='purchase_return',
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='purchase_return',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_entry', to='transactions.purchasereturn'),
        ),
    ]
