# Generated by Django 5.0.6 on 2026-01-23 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0014_remove_customerpayment_purchase_return_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierpayment',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='transactions.purchaseinvoice'),
        ),
        migrations.AlterField(
            model_name='supplierpayment',
            name='payment_mode',
            field=models.CharField(choices=[('CASH', 'Cash'), ('UPI', 'UPI'), ('CHEQUE', 'Cheque'), ('BANK', 'Bank Transfer'), ('DEBIT_NOTE', 'Debit Note')], default='CASH', max_length=20),
        ),
    ]
