# Generated by Django 6.0 on 2026-02-21 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0016_sprint3_immutable_invoice_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoice',
            name='amended_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amendments', to='transactions.purchaseinvoice'),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='amended_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amendments', to='transactions.salesinvoice'),
        ),
    ]
