# Generated by Django 5.0.6 on 2025-12-14 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0003_customer_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='default_credit_period',
            field=models.IntegerField(default=30, help_text='Default credit days for this supplier'),
        ),
    ]
