# Generated by Django 5.0.6 on 2025-12-25 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0005_customer_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='wallet_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
