# Generated by Django 6.0 on 2026-02-21 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0007_alter_category_id_alter_customer_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='moving_average_price',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Weighted-average cost, recalculated on purchase inward.', max_digits=15),
        ),
    ]
