# Generated by Django 6.0 on 2026-02-21 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('account_type', models.CharField(choices=[('ASSET', 'Asset'), ('LIABILITY', 'Liability'), ('EQUITY', 'Equity'), ('INCOME', 'Income'), ('EXPENSE', 'Expense')], max_length=20)),
                ('is_system_account', models.BooleanField(default=False, help_text='System accounts cannot be deleted.')),
            ],
            options={
                'ordering': ['account_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GLEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.DecimalField(decimal_places=2, default=0, help_text='Debit amount (positive or zero).', max_digits=15)),
                ('credit', models.DecimalField(decimal_places=2, default=0, help_text='Credit amount (positive or zero).', max_digits=15)),
                ('posting_date', models.DateTimeField(auto_now_add=True)),
                ('reference_type', models.CharField(help_text="Source document type, e.g. 'PurchaseInvoice'.", max_length=50)),
                ('reference_id', models.PositiveIntegerField(help_text='PK of the source document.')),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gl_entries', to='accounting.account')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['reference_type', 'reference_id'], name='idx_gl_ref_doc')],
            },
        ),
    ]
